import './globals.css'
import type { Metadata } from 'next'
import { Inter } from 'next/font/google'
import Link from 'next/link'

const inter = Inter({ subsets: ['latin'] })

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body className={inter.className}>
          <nav className="navBar">
            <p id="icon" className='welcome'>Ergo</p>
            <Link href='/'>Home</Link>
            <Link href='/notes'>Notes</Link>
            <Link href='/tasks'>Tasks</Link>
            <Link href='/visualizer'>Visualizer</Link>
          </nav>
        {children}
      </body>
    </html>
  )
}